apiVersion: v1
kind: Namespace
metadata:
  name: my-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-storage
  namespace: my-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management-app
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-management-app
  template:
    metadata:
      labels:
        app: order-management-app
    spec:
      containers:
      - name: order-management-app
        image: 1025software/ordermgmtexpress:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: sqlite-storage
          mountPath: /src/storage
      volumes:
      - name: sqlite-storage
        persistentVolumeClaim:
          claimName: sqlite-storage
