stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t 1025software/ordermgmtexpress:latest .
    - docker push 1025software/ordermgmtexpress:latest

deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - echo $GCP_SERVICE_ACCOUNT_KEY | base64 -d > gcp-service-account.json
    - gcloud auth activate-service-account --key-file gcp-service-account.json
    - gcloud container clusters get-credentials ordermgmtsystem --zone us-east1
    - kubectl apply -f deployment.yaml
    - kubectl apply -f service.yaml
  only:
    - main